version: '3.8'

services:
  codementor-ai:
    build: .
    container_name: codementor_ai
    ports:
      - "8501:8501" # Streamlit
      - "8000:8000" # MCP Server
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
