from typing import Dict, Any
from pydantic import BaseModel, Field
from agents.base_agent import BaseAgent
from core.utils import safe_json_loads

class ReflectionOutput(BaseModel):
    is_optimal: bool = Field(description="Does this solution meet all constraints and edge cases?")
    critique: str = Field(description="Constructive criticism of the provided solution/code.")
    revised_code: str = Field(description="The optimally revised code incorporating critique.")

class ReflectionAgent(BaseAgent):
    \"\"\"
    Acts as a Principal Engineer / Reviewer.
    Critiques the initial solutions generated by the Solver Agent.
    \"\"\"

    SYSTEM_PROMPT = \"\"\"
    You are a Principal Software Engineer known for strict code reviews.
    You will be provided with a Problem Statement and a Proposed Code Solution.
    Your job is to intensely critique it:
    1. Are there hidden edge cases?
    2. Is it truly optimal in Big O time/space?
    3. Is it idiomatic and clean?
    Provide your critique and rewrite the code if flaws are found or if you can improve performance.
    Output exclusively as JSON.
    \"\"\"

    def run(self, problem_statement: str, initial_code: str) -> Dict[str, Any]:
        self.logger.info("Executing Reflection phase...")

        prompt = f"Problem Statement:\\n{problem_statement}\\n\\n"
        prompt += f"Proposed Solution to Evaluate:\\n{initial_code}\\n\\n"
        
        try:
            response_text = self._call_llm(
                system_instruction=self.SYSTEM_PROMPT,
                prompt=prompt,
                schema=ReflectionOutput
            )
            return safe_json_loads(response_text)
        except Exception as e:
            self.logger.error(f"Reflection Agent failed: {e}")
            return {"error": str(e)}
